### ISSUE TITLE
Can we track size reasons in a separate repo?

### ISSUE THREAD

**Issue by jonabc** [levindixon/pr-size-helper-action#1]
My team has separate repos for product code and team planning+tracking.  Is it possible to add a configuration option to open an issue tracking the reasons for large PR sizes in a separate repo from where PRs are opened?

**Comment by levindixon** [comment]
Thanks @jonabc! Funny you should ask, my team also has separate repos for product code and team planning 😂

**Comment by joshhale** [comment]
Same! +1 to this feature request 😁
